
questionare_versions = {
    '0.1.0': {'age', 'chronic_cancer', 'chronic_diabetes', 'chronic_hypertension',
              'chronic_ischemic_heart_disease_or_stroke', 'chronic_kidney_failure', 'chronic_lung_disease', 'city_town',
              'continue', 'exposure_met_people', 'flatmates', 'flatmates_over_70', 'flatmates_under_18', 'hospitalized',
              'insulation_exposure_date', 'insulation_patient_number', 'insulation_returned_from_abroad_date',
              'insulation_status', 'sex', 'smoking', 'street', 'symptoms_breath_shortness', 'symptoms_clogged_nose',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_fatigue', 'symptoms_headache', 'symptoms_infirmity',
              'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_sore_throat',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'toplevel_symptoms_stomach',
              'toplevel_symptoms_tiredness', 'version', 'work_serve_over_10'},
    '0.2.0': {'age', 'chronic_cancer', 'chronic_diabetes', 'chronic_hypertension',
              'chronic_ischemic_heart_disease_or_stroke', 'chronic_kidney_failure', 'chronic_lung_disease', 'city_town',
              'continue', 'exposure_met_people', 'flatmates', 'flatmates_over_70', 'flatmates_under_18', 'hospitalized',
              'insulation_exposure_date', 'insulation_patient_number', 'insulation_returned_from_abroad_date',
              'insulation_status', 'locale', 'sex', 'smoking', 'street', 'symptoms_breath_shortness',
              'symptoms_clogged_nose', 'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_fatigue',
              'symptoms_headache', 'symptoms_infirmity', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_sore_throat', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'toplevel_symptoms_stomach', 'toplevel_symptoms_tiredness', 'version',
              'work_serve_over_10'},
    '0.2.1': {'age', 'chronic_cancer', 'chronic_diabetes', 'chronic_hypertension',
              'chronic_ischemic_heart_disease_or_stroke', 'chronic_kidney_failure', 'chronic_lung_disease', 'city_town',
              'continue', 'exposure_met_people', 'flatmates', 'flatmates_over_70', 'flatmates_under_18', 'hospitalized',
              'insulation_exposure_date', 'insulation_patient_number', 'insulation_returned_from_abroad_date',
              'insulation_status', 'locale', 'sex', 'smoking', 'street', 'symptoms_breath_shortness',
              'symptoms_clogged_nose', 'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_fatigue',
              'symptoms_headache', 'symptoms_infirmity', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_sore_throat', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'toplevel_symptoms_stomach', 'toplevel_symptoms_tiredness', 'version',
              'work_serve_over_10', 'xxx'},
    '1.0.1': {'age', 'chronic_cancer', 'chronic_diabetes', 'chronic_hypertension', 'chronic_immune_system_suppression',
              'chronic_ischemic_heart_disease_or_stroke', 'chronic_kidney_failure', 'chronic_lung_disease', 'city_town',
              'dateFirstReport', 'diagnosed_location', 'exposure_status', 'general_feeling', 'insulation_exposure_date',
              'insulation_patient_number', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'locale', 'met_above_18', 'met_under_18', 'numPreviousReports', 'sex', 'smoking',
              'street', 'symptoms_breath_shortness', 'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough',
              'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss',
              'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'toplevel_symptoms_stomach', 'version', 'xxx'},
    '1.1.0': {'age', 'chronic_cancer', 'chronic_diabetes', 'chronic_hypertension', 'chronic_immune_system_suppression',
              'chronic_ischemic_heart_disease_or_stroke', 'chronic_kidney_failure', 'chronic_lung_disease', 'city_town',
              'dateFirstReport', 'diagnosed_location', 'exposure_status', 'general_feeling', 'insulation_exposure_date',
              'insulation_patient_number', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'locale', 'met_above_18', 'met_under_18', 'numPreviousReports', 'sex', 'smoking',
              'street', 'symptoms_breath_shortness', 'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough',
              'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss',
              'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'toplevel_symptoms_stomach', 'version', 'xxx'},
    '2.0.0': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'exposure_status',
              'general_feeling', 'insulation_exposure_date', 'insulation_patient_number', 'insulation_reason',
              'insulation_returned_from_abroad_date', 'insulation_start_date', 'locale', 'met_above_18',
              'met_under_18', 'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression',
              'precondition_chronic_ischemic_heart_disease_or_stroke', 'precondition_chronic_kidney_failure',
              'precondition_chronic_lung_disease', 'precondition_smoking', 'preconditions_received', 'sex', 'street',
              'symptoms_breath_shortness', 'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough',
              'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss',
              'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'version', 'xxx'},
    '2.0.1': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'locale',
              'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version'},
    '2.0.2': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'feel_good', 'general_feeling', 'insulation_exposure_date',
              'insulation_patient_number', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'locale', 'met_above_18', 'met_under_18', 'none', 'notificationsEnabled',
              'numPreviousReports', 'precondition_chronic_cancer', 'precondition_chronic_diabetes',
              'precondition_chronic_hypertension', 'precondition_chronic_immune_system_suppression',
              'precondition_chronic_ischemic_heart_disease_or_stroke', 'precondition_chronic_kidney_failure',
              'precondition_chronic_lung_disease', 'precondition_smoking', 'preconditions_received', 'sex', 'street',
              'symptoms_breath_shortness', 'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough',
              'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss',
              'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'version', 'xxx'},
    '2.0.3': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'feel_good', 'general_feeling', 'insulation_reason',
              'insulation_returned_from_abroad_date', 'insulation_start_date', 'locale', 'met_above_18', 'met_under_18',
              'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version', 'xxx'},
    '2.0.4': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'feel_bad', 'general_feeling', 'insulation_reason',
              'insulation_returned_from_abroad_date', 'insulation_start_date', 'locale', 'met_above_18', 'met_under_18',
              'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version'},
    '2.0.5': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'locale', 'met_above_18', 'met_under_18', 'notificationsEnabled',
              'numPreviousReports', 'precondition_chronic_cancer', 'precondition_chronic_diabetes',
              'precondition_chronic_hypertension', 'precondition_chronic_immune_system_suppression',
              'precondition_chronic_ischemic_heart_disease_or_stroke', 'precondition_chronic_kidney_failure',
              'precondition_chronic_lung_disease', 'precondition_smoking', 'preconditions_received', 'sex', 'street',
              'symptoms_breath_shortness', 'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion',
              'symptoms_diarrhea', 'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough',
              'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss',
              'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough',
              'toplevel_symptoms_pains', 'version'},
    '2.1.0': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'locale',
              'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'recaptcha', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version', 'xxx'},
    '2.2.0': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'FALSE', 'feel_good', 'general_feeling', 'insulation_exposure_date',
              'insulation_patient_number', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'layout', 'locale', 'medical_staff_member', 'met_above_18', 'met_under_18',
              'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'recaptcha', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version'},
    '2.2.2': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'feel_good', 'general_feeling', 'insulation_exposure_date',
              'insulation_patient_number', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'layout', 'locale', 'medical_staff_member', 'met_above_18', 'met_under_18',
              'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'recaptcha', 'sex', 'street', 'symptoms_breath_shortness', 'symptoms_chills',
              'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea', 'symptoms_dry_cough',
              'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain', 'symptoms_nausea_and_vomiting',
              'symptoms_smell_taste_loss', 'symptoms_sore_throat', 'symptoms_tiredness_or_fatigue', 'temperature',
              'toplevel_symptoms_cough', 'toplevel_symptoms_pains', 'version'},
    '2.5.4': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_reason', 'insulation_returned_from_abroad_date',
              'insulation_start_date', 'layout', 'locale', 'medical_staff_member', 'met_above_18', 'met_under_18',
              'notificationsEnabled', 'numPreviousReports', 'precondition_chronic_cancer',
              'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'
              },
    '2.5.5': {'age', 'alias', 'city_town', 'dateFirstReport', 'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_reason', 'insulation_start_date', 'layout', 'locale',
              'medical_staff_member', 'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'},
    '2.5.6': {'age', 'alias', 'city_town', 'dateFirstReport',
              'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'layout', 'locale',
              'medical_staff_member', 'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'},
    '2.5.8': {'age', 'alias', 'city_town', 'dateFirstReport',
              'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'layout', 'locale',
              'medical_staff_member', 'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'},
    '2.5.9': {'age', 'alias', 'city_town', 'dateFirstReport',
              'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'layout', 'locale',
              'medical_staff_member', 'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'},
    '2.6.0': {'age', 'alias', 'city_town', 'covid19_check_date','covid19_check_result','dateFirstReport',              'diagnosed_location', 'engagementSource',
              'exposure_status', 'general_feeling', 'insulation_exposure_date', 'insulation_patient_number',
              'insulation_reason', 'insulation_returned_from_abroad_date', 'insulation_start_date', 'layout', 'locale',
              'medical_staff_member', 'met_above_18', 'met_under_18', 'notificationsEnabled', 'numPreviousReports',
              'precondition_chronic_cancer', 'precondition_chronic_diabetes', 'precondition_chronic_hypertension',
              'precondition_chronic_immune_system_suppression', 'precondition_chronic_ischemic_heart_disease_or_stroke',
              'precondition_chronic_kidney_failure', 'precondition_chronic_lung_disease', 'precondition_smoking',
              'preconditions_received', 'served_public_last_fortnight', 'sex', 'street', 'symptoms_breath_shortness',
              'symptoms_chills', 'symptoms_clogged_nose', 'symptoms_confusion', 'symptoms_diarrhea',
              'symptoms_dry_cough', 'symptoms_headache', 'symptoms_moist_cough', 'symptoms_muscles_pain',
              'symptoms_nausea_and_vomiting', 'symptoms_smell_taste_loss', 'symptoms_sore_throat',
              'symptoms_tiredness_or_fatigue', 'temperature', 'toplevel_symptoms_cough', 'toplevel_symptoms_pains',
              'version'},  
}
